login page
Favvie/farmersMarketPlace pull request #9
Opened 2024-10-12 19:53 UTC by Gifftybabe

2024-10-14 09:11 UTC, Favvie requested changes, later dismissed
There are two background images in your screen.

Please refactor to the form component in shadcn

2024-10-14 13:52 UTC, Favvie commented on client/Components/Registration.tsx
> +          {/* <div className="flex items-center space-x-4">
Please remove the unused code

2024-10-14 13:54 UTC, Favvie commented on client/Components/Registration.tsx
> +    return !isNaN(parseFloat(value)) && isFinite(+value))
remove the bracket, and add a ; it is causing your code to break

2024-10-14 13:57 UTC, Favvie commented on client/Components/Registration.tsx
> +    return !isNaN(parseFloat(value)) && isFinite(+value))
![Uploading Screenshot 2024-10-14 at 14.56.15.png…]()

2024-10-14 14:04 UTC, Belloabraham121 commented on client/Components/Registration.tsx
> +    return !isNaN(parseFloat(value)) && isFinite(+value))
![WhatsApp Image 2024-10-14 at 15 02 50_7b2e6006](https://github.com/user-attachments/assets/ce6c5883-b859-4362-9f33-c79d09f417e1)
![WhatsApp Image 2024-10-14 at 15 03 18_27a670c1](https://github.com/user-attachments/assets/e194e664-c89e-476c-a798-69ff6800c8ba)

2024-10-14 16:12 UTC, Gifftybabe commented
> There are two background images in your screen.
> 
> Please refactor to the form component in sha

One of the images removed already

2024-10-16 00:11 UTC, obah approved these changes

2024-10-16 08:40 UTC, merged